SELECT 
    COUNT(DISTINCT customernumber) AS totalcustomers
FROM
    customers_view;

SELECT 
    *
FROM
    customers_view
WHERE
    orderNumber IS NULL;

-- Top 10 customers by Total Payment Amount
SELECT 
    customerNumber, customerName, totalPayments
FROM
    customers_view
GROUP BY customerNumber , customerName
ORDER BY totalPayments DESC
LIMIT 10;
-- Of the top 10 customer #141 'Euro+ Shopping Channel' payed the highest amount at $715,738.98 while customer #146 'Saveley & Henriot, Co.' payed the least with $130,305.35

SELECT 
    customerNumber,
    customerName,
    COUNT(orderNumber) AS orderCount
FROM
    customers_view
WHERE
    status IN ('Shipped' , 'Resolved', 'Disputed')
GROUP BY customerNumber
ORDER BY orderCount DESC;
-- 'Bavarian Collectables Imports, Co.' has only 1 completed order 
-- 'Euro+ Shopping Channel' has the most orders with 24


-- Customer Acquisition and Retention: The following query tracks customer acquisition and retention year over year
-- Includes orders of all statuses
WITH customers_03 AS (
    SELECT COUNT(DISTINCT customerNumber) AS newCustomers
    FROM customers_view
    WHERE YEAR(orderDate) = 2003
),
customers_04 AS (
    SELECT COUNT(DISTINCT customerNumber) AS newCustomers
    FROM customers_view
    WHERE YEAR(orderDate) = 2004 
    AND customerNumber NOT IN (SELECT customerNumber FROM customers_view WHERE YEAR(orderDate) = 2003)
),
customers_05 AS (
    SELECT COUNT(DISTINCT customerNumber) AS newCustomers
    FROM customers_view
    WHERE YEAR(orderDate) = 2005 
    AND customerNumber NOT IN (SELECT customerNumber FROM customers_view WHERE YEAR(orderDate) IN (2003, 2004))
),
retained_04 AS (
    SELECT COUNT(DISTINCT customerNumber) AS retainedCustomers
    FROM customers_view
    WHERE YEAR(orderDate) = 2004 
    AND customerNumber IN (SELECT customerNumber FROM customers_view WHERE YEAR(orderDate) = 2003)
),
retained_05 AS (
    SELECT COUNT(DISTINCT customerNumber) AS retainedCustomers
    FROM customers_view
    WHERE YEAR(orderDate) = 2005 
    AND customerNumber IN (SELECT customerNumber FROM customers_view WHERE YEAR(orderDate) IN (2003, 2004))
)
SELECT 
    2003 AS year, newCustomers, 0 AS retainedCustomers FROM customers_03
UNION ALL
SELECT 
    2004 AS year, newCustomers, retainedCustomers FROM customers_04, retained_04
UNION ALL
SELECT 
    2005 AS year, newCustomers, retainedCustomers FROM customers_05, retained_05
ORDER BY year DESC;
-- Mint Classics acquired 24 new customers in 2004 and none by the end of May 2005
-- They also retained roughly 88% of customers in 2004 from the previous year and in 2005 roughly 49% overall
-- Retention dropped by half in 2005 but given that records end in May of that year these numbers could give an incomplete picture

--------------------------------------- -- Geographic and Credit Distribution -- ---------------------------------------------------

-- Total Payments by Country
SELECT country, SUM(DISTINCT totalPayments) AS paymentPerCountry
FROM customers_view
GROUP BY country
ORDER BY paymentPerCountry DESC;
-- Most revenue is overwhelmingly generated by the United States at $3,040,029.52 with it's nearest competitor being Spain at $994,438.53
-- The following countries have made no payments: Israel, The Netherlands, Poland, Portugal, Russia, and South Africa

SELECT 
    country, COUNT(DISTINCT customerNumber) AS customerCount
FROM
    customers_view
GROUP BY country
ORDER BY customerCount DESC;
-- Again, the U.S. is overwhelmingly in the lead with 36 customers while Germany and France occupy a distant 2nd and 3rd with 13 and 12 respectively
-- The following countries only have one customer buying products from Mint Classics: Hong Kong, Israel, The Netherlands, Philippines, Poland, Russia, and South Africa

-- Total Payments by Credit Limit Range: Splits the range of customer credit limits into quartiles and calculates total payments for each
WITH creditQuartile AS (
    SELECT
        customerNumber,
        customerName,
        creditLimit,
        totalPayments,
        NTILE(4) OVER (ORDER BY creditLimit) AS quartileCredit
    FROM customers_view
    GROUP BY customerNumber, customerName, creditLimit
)
SELECT CASE
        WHEN quartileCredit = 1 THEN 'Low Credit Limit (1st Quartile)'
        WHEN quartileCredit = 2 THEN 'Moderate Credit Limit (2nd Quartile)'
        WHEN quartileCredit = 3 THEN 'High Credit Limit (3rd Quartile)'
        ELSE 'Premium Credit Limit (4th Quartile)'
    END AS creditCategory,
    SUM(DISTINCT totalPayments) AS totalPayments
FROM creditQuartile
GROUP BY creditCategory
ORDER BY totalPayments DESC;
-- As expected the ordering for total payments of each quartile follows the quartile rank
-- Low (1st Quartile): $169,126.62, Moderate (2nd Quartile): $1,815,872.06, High (3rd Quartile): $2,452,846.21, Premium (4th Quartile): $4,415,994.34 



-------------------------------------------------------------------------- Sales Rep, Order, and Payment Analysis -----------------------------------------------------------------------------------
-- Total Revenue made by The Mint Classics Company from March of 2003 to May of 2005
SELECT SUM(DISTINCT totalPayments) FROM customers_view;-- Mint Classics made $8,853,839.23 in total sales over the recorded period

SELECT 
    salesRepEmployeeNumber,
    lastName,
    firstName,
    SUM(DISTINCT totalPayments) AS totalPayments
FROM
    customers_view
WHERE
    salesRepEmployeeNumber IS NOT NULL
GROUP BY salesRepEmployeeNumber
ORDER BY totalPayments DESC;
-- The 2 best sales reps have totals hovering around a million dollars in revenue a piece
-- They are Gerard Hernandez with $1,112,003.81 and Leslie Jennings with $989,906.55
-- At the bottom end Martin Gerard, Julie Firrelli, and Leslie Thompson all generate below $400,000 in total received payments

SELECT 
    AVG(DATEDIFF(shippedDate, orderDate)) AS avgDaysToShip
FROM
    customers_view
WHERE
    shippedDate IS NOT NULL;
-- On average it takes about 3.76 days to ship items to customers

SELECT 
    YEAR(orderDate) AS year, COUNT(orderNumber) AS totalOrders
FROM
    customers_view
WHERE
    status IN ('Shipped' , 'Resolved', 'Disputed')
GROUP BY year
ORDER BY year DESC;
-- 2004 has the most completed orders at 146 while 2005 shows a steep decline at 55
-- However, given that records only exist for dates between 2003-03-01 & 2005-05-31, these results may not be significant

SELECT 
    YEAR(orderDate) AS year,
    MONTH(orderDate) AS month,
    status,
    COUNT(orderNumber) AS totalOrders
FROM
    customers_view
GROUP BY year , month , status
ORDER BY year DESC , month DESC;
-- All cancelled orders occur in the third quarter of 2003 and the second quarter of 2004
-- As expected most completed orders occur during the 4th quarter (Holiday Season)

SELECT 
    YEAR(latestPaymentDate) AS year,
    MONTH(latestPaymentDate) AS month,
    SUM(DISTINCT totalPayments) AS totalPayments
FROM
    customers_view
WHERE
    latestPaymentDate IS NOT NULL
GROUP BY year , month
ORDER BY year DESC , month DESC;
-- Payments by year - (2005: $3,939,892.30, 2004: $4,868,466.14, 2003: $45,480.79) - shows a substantial jump after 2003
-- The highest payments in 2005 occurred in May at $1,449,387.78 while for 2004 payments peaked in December at $1,438,778.88 possibly due to holiday sales
